### ISSUE TITLE
Feature: Provide required data in repo or Add a build script

### ISSUE THREAD

**Issue by StormTide** [bcgov/groundwater-levels#1]
Where an app relies on data (as here), ideally the data should be open licensed and accessible on an url endpoint. If the data is not large (<10Mb or so), include it in the repository. Otherwise for larger datasets, a build/bootstrap script to easily populate the required data, with an install.md or build.md that describes its operation. This will help app consumers get up and running with the visualization and more easily contribute improvements.

**Comment by ateucher** [comment]
Thanks very much for this. The raw groundwater level data is not currently under an open license, and too big for the repository (>600MB). 

We do have the aggregated monthly data available under the B.C. Open Government license, and I've updated the cleaning script and README.md to more easily allow using this (https://github.com/bcgov/groundwater_levels/commit/f94c92bd39df282c7071e5d009e630efe04b6472).

As for the metadata (Well attribute data and the Natural Resource Operation regions), they are available under the B.C. Open Government license but are not directly downloadable as they are assembled by the Data Distribution Service (eg. https://apps.gov.bc.ca/pub/dwds/addProductsFromExternalApplication.do?productTypeId=0&productId=9695). Uncompressed they are quite large (>40MB), but it might work to include them in the repo compressed.

**Comment by StormTide** [comment]
Its not general availability yet, but https://git-lfs.github.com/ might be good for this purpose when it fully launches.

**Comment by ateucher** [comment]
Thanks Kevin. Looks very promising!
