### ISSUE TITLE
Implement interactive data visualization using R & R Markdown

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/groundwater-levels#7]

**Comment by stephhazlitt** [comment]
This issue is a paid opportunity through the [BCDevExchange](https://bcdevexchange.org/). To apply, visit the [opportunity page](https://bcdevexchange.org/opportunities/cwu/opp-trends-in-groundwater-levels-data-visualization-using-r) and submit a proposal by 16:00 Pacific Time, Wednesday, September 26, 2018.

---
Remake and simplification of existing D3 (JavaScript) interactive data visualization reporting Trends in Groundwater Levels using [R](https://r-project.org) and [R Markdown](https://rmarkdown.rstudio.com/). 

See the existing D3 (JavaScript) Trends in Groundwater Levels interactive data visualization: [Trends in Groundwater Levels - Environmental Reporting BC](http://www.env.gov.bc.ca/soe/indicators/water/groundwater-levels.html). The remake project will result in a data visualization with only some of the current functionality maintained&mdash;an interactive map with markers, tooltip on hover and a modal window with pre-prepared content on click. The remake will also involve a few enhancements, such as including natural resource region polygons on the map and adding direct links in an observation well modal window to the [Groundwater Level Data Interactive Map](https://governmentofbc.maps.arcgis.com/apps/webappviewer/index.html?id=b53cb0bf3f6848e79d66ffd09b74f00d).

#### Data Visualization Design/Layout

Datavis design should include a larger version of the existing map showing observation well markers coloured by trend category, with natural resource region polygons (enhancement). It should be 900px wide, and not more than 900px high.

![image](https://user-images.githubusercontent.com/7143861/45722083-a20f5080-bb5f-11e8-90aa-6d136b0d297a.png)
![image](https://user-images.githubusercontent.com/7143861/45722088-a6d40480-bb5f-11e8-807f-ccbb040b5aaa.png)

#### Functionality

- Hovering mouse over a natural resource region polygon on the map should bring up a tooltip with region name.
- Hovering mouse over an observation well marker on the map should bring up a tooltip with region name, observation well name and trend category.
- Clicking on a natural resource region polygon should open a modal window with region name and a bar chart showing the number of observation wells by trend category for the region. 
- Clicking on an observation well marker should open a modal window with region name, observation well name, two plots&mdash;the monthly groundwater level pattern and long-term trends&mdash;and a link to the same observation well in the [Groundwater Level Data Interactive Map](https://governmentofbc.maps.arcgis.com/apps/webappviewer/index.html?id=b53cb0bf3f6848e79d66ffd09b74f00d).

The British Columbia summary pie and bar charts in the [existing interactive data visualization](http://www.env.gov.bc.ca/soe/indicators/water/groundwater-levels.html) will not be included in the remake&mdash;they will appear elsewhere in future versions of the indicator.

#### Technologies

- Solution should be done using R and R Markdown that renders an html file.
- Anticipated/suggested packages and approaches include R Markdown, `Leaflet for R`, `ggplot2` and other `tidyverse` packages. We are open to other suggestions, however we are not seeking a _Shiny_ implementation at this time.

#### Resources

- Run the [groundwater-levels-indicator update-2018 branch](https://github.com/bcgov/groundwater-levels-indicator/tree/update-2018) and use the outputs to populate the data visualization
- The groundwater well attribute data used for the indicator is obtained from the [B.C. Data Catalogue](https://catalogue.data.gov.bc.ca/dataset/e4731a85-ffca-4112-8caf-cb0a96905778), provided under the Open Government Licence - British Columbia
- The groundwater level data used for the indicator is obtained from the  [B.C. Data Catalogue](https://catalogue.data.gov.bc.ca/dataset/57c55f10-cf8e-40bb-aae0-2eff311f1685), provided under the Open Government Licence - British Columbia, using the [`bcgroundwater` R package](https://github.com/bcgov/bcgroundwater)
- Natural Resource Region boundaries for use in the map are available in the [`bcmaps` R package](https://cran.r-project.org/package=bcmaps)
- The Groundwater Level Data Interactive Map links for the individual wells are available from the [Groundwater Level Data Interactive Map](https://governmentofbc.maps.arcgis.com/apps/webappviewer/index.html?id=b53cb0bf3f6848e79d66ffd09b74f00d)

**Comment by stephhazlitt** [comment]
Hi folks, I am the contact for this Code With Us opportunity. Please post any questions you have here and I'll do my best to respond promptly.

**Comment by iuriishamkin** [comment]
Hello Stephanie,

Is it possible to get a copy of your print template for the markdown file?
`envreportutils.internal::print_ver` is not accessible. 


Sincerely,
Iurii

**Comment by stephhazlitt** [comment]
Hi @iuriishamkin, thanks for your question. Unfortunately the print template is in one of our internal packages. If you replace `output: envreportutils.internal::print_ver` with `output: pdf_document` the Rmd should knit for you?

**Comment by iuriishamkin** [comment]
@stephhazlitt I've already done! Thanks for a prompt reply. 

I was getting this error so I thougth theme was edited by a template:
> ` Error in width_cm(guide$keywidth %||% theme$legend.key.width %||% theme$legend.key.size) : Unknown input`

**Comment by ateucher** [comment]
Hi @iuriishamkin - just stepping in here for @stephhazlitt as she's unavailable today. The Rmd renders for me without the template (the template doesn't change anything with respect to ggplot2 themes so I think your error is unrelated to the template).

Have you installed the **envreportutils** pacakge (`remotes::install_github("bcgov/envreportutils")`)? That package does define themes and is available publicly.

Cheers,
Andy

**Comment by iuriishamkin** [comment]
@ateucher you're completely right! 


This issue was caused by missing API key for `get_googlemap()` calls in `04_output.R`. Because of that `summary_map` wasn't initialized properly. 


Maybe it's worth adding a mention about a key in the comment for those not familiar with this API? Also, `xtable` library used in markdown file is missing in the package list. Just a heads up.

Regards,
Iurii

**Comment by ateucher** [comment]
Ok, nice sleuthing @iuriishamkin. I think the requirement for a Google Maps API key for `ggmap` is new; I believe Google used to let you do a certain number of queries without one. We will document that.

**Comment by iuriishamkin** [comment]
@ateucher my pleasure! It's an interesting project to dig into.

**Comment by stephhazlitt** [comment]
Thanks to everyone for your interest in helping us out with this Code With Us opportunity. 

The opportunity closed on September 26th&mdash;we received **8** proposals. All proposals were scored against the [proposal evaluation criteria](https://bcdevexchange.org/opportunities/cwu/opp-trends-in-groundwater-levels-data-visualization-using-r). The opportunity has been assigned to @steffilazerte who had the highest scoring proposal.

If you would like feedback on your proposal, please feel free to contact me at the email address in my @stephhazlitt profile. 

Thanks again to everyone.

**Comment by ateucher** [comment]
This is complete as of #4
